# Permalinks
permalink:        pretty

# Setup
title:            Collect Your Data
tagline:          'Collect your data'
description:      'Collect your data'
url:              http://collectyourdata.github.io
baseurl:          /

author:
  name:           'Collect Your Data'
#  url:            

paginate:         5

#github:
  repo:           https://github.com/collectyourdata
