# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Collect Your Data
tagline:          'Collect your data'
description:      'Collect your data'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Collect Your Data'
#  url:            

paginate:         5

# Custom vars
version:          0.0.1

#github:
#  repo:           
